# Generated by Django 4.0.3 on 2022-03-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0002_alter_bugtracker_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugtracker',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
